
apiVersion: v1
kind: Namespace
metadata:
  name: k8s-ephemeral-storage-metrics

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ephemeral-storage-metrics
  namespace: k8s-ephemeral-storage-metrics
  labels:
    k8s-app: ephemeral-storage-metrics
spec:
  selector:
    matchLabels:
      k8s-app: ephemeral-storage-metrics
  template:
    metadata:
      labels:
        k8s-app: ephemeral-storage-metrics
    spec:
      containers:
        - name: metrics
          image: registry.lab.com/k8s-ephemeral-storage-metrics:latest
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
            - containerPort: 56268
              protocol: TCP
              name: debug
          env:
            - name: CURRENT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName


---

apiVersion: v1
kind: Service
metadata:
  name: ephemeral-storage-metrics
  namespace: k8s-ephemeral-storage-metrics
  labels:
    k8s-app: ephemeral-storage-metrics
spec:
  type: LoadBalancer
  ports:
    - port: 9100
      targetPort: metrics
      protocol: TCP
      name: metrics
    - port: 56268
      targetPort: debug
      protocol: TCP
      name: debug
  selector:
    k8s-app: ephemeral-storage-metrics