apiVersion: v1
kind: Namespace
metadata:
  name: k8s-ephemeral-storage-metrics

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ephemeral-storage-metrics
  namespace: k8s-ephemeral-storage-metrics
  labels:
    k8s-app: k8s-ephemeral-storage-metrics
spec:
  selector:
    matchLabels:
      k8s-app: k8s-ephemeral-storage-metrics
  template:
    metadata:
      labels:
        k8s-app: k8s-ephemeral-storage-metrics
    spec:
      containers:
        - name: metrics
          image: registry.lab.com/k8s-ephemeral-storage-metrics:latest
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          env:
            - name: CURRENT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName


---

apiVersion: v1
kind: Service
metadata:
  name: k8s-ephemeral-storage-metrics
  namespace: k8s-ephemeral-storage-metrics
  labels:
    k8s-app: k8s-ephemeral-storage-metrics
spec:
  type: ClusterIP
  ports:
    - port: 9100
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    k8s-app: k8s-ephemeral-storage-metrics


---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: k8s-ephemeral-storage-metrics
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    app: k8s-ephemeral-storage-metrics
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - k8s-ephemeral-storage-metrics
  selector:
    matchLabels:
      k8s-app: k8s-ephemeral-storage-metrics
  endpoints:
    - port: metrics
      interval: 15s