apiVersion: v1
kind: Namespace
metadata:
  name: k8s-ephemeral-storage-metrics

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-ephemeral-storage-metrics
rules:
  - apiGroups: [ "" ]
    resources: [ "*" ]
    verbs: [ "*" ]


---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: k8s-ephemeral-storage-metrics
  name: k8s-ephemeral-storage-metrics
  namespace: k8s-ephemeral-storage-metrics

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: k8s-ephemeral-storage-metrics
subjects:
  - kind: ServiceAccount
    name: k8s-ephemeral-storage-metrics
    namespace: k8s-ephemeral-storage-metrics
roleRef:
  kind: ClusterRole
  name: k8s-ephemeral-storage-metrics
  apiGroup: rbac.authorization.k8s.io


---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ephemeral-storage-metrics
  namespace: k8s-ephemeral-storage-metrics
  labels:
    k8s-app: k8s-ephemeral-storage-metrics
spec:
  selector:
    matchLabels:
      k8s-app: k8s-ephemeral-storage-metrics
  template:
    metadata:
      labels:
        k8s-app: k8s-ephemeral-storage-metrics
    spec:
      containers:
        - name: metrics
          image: registry.lab.com/k8s-ephemeral-storage-metrics:latest
          resources:
            limits:
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 200Mi
          ports:
            - name: metrics
              containerPort: 9100
              protocol: TCP
          env:
            - name: CURRENT_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName


---

apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: k8s-ephemeral-storage-metrics
  # Change this to the namespace the Prometheus instance is running in
  namespace: monitoring
  labels:
    release: kube-prometheus
    k8s-app: k8s-ephemeral-storage-metrics
spec:
  namespaceSelector:
    matchNames:
      - k8s-ephemeral-storage-metrics
  selector:
    matchLabels:
      k8s-app: k8s-ephemeral-storage-metrics
      release: kube-prometheus
  podMetricsEndpoints:
    - port: metrics
      interval: 15s