# REF https://skaffold.dev/docs/references/yaml/?version=v2beta29
apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: k8s-ephemeral-storage-metrics
      docker:
        dockerfile: Dockerfile


profiles:
  - name: staging
    deploy:
      helm:
        releases:
          - name: k8s-ephemeral-storage-metrics-staging
            namespace: k8s-ephemeral-storage-metrics-staging
            createNamespace: true
            chartPath: 'charts/k8s-ephemeral-storage-metrics'
            artifactOverrides:
              image: k8s-ephemeral-storage-metrics
            overrides:
              log_level: debug
              deploy_type: Deployment

    portForward:
      - resourceType: Deployment
        resourceName: k8s-ephemeral-storage-metrics
        namespace: k8s-ephemeral-storage-metrics-staging
        port: 9100
        localPort: 9100

  - name: dev
    deploy:
      helm:
        releases:
          - name: k8s-ephemeral-storage-metrics-dev
            namespace: k8s-ephemeral-storage-metrics-dev
            createNamespace: true
            chartPath: 'charts/k8s-ephemeral-storage-metrics'
            artifactOverrides:
              image: k8s-ephemeral-storage-metrics
            overrides:
              log_level: debug
              deploy_type: Deployment

    portForward:
      - resourceType: Deployment
        resourceName: k8s-ephemeral-storage-metrics
        namespace: k8s-ephemeral-storage-metrics-dev
        port: 9100
        localPort: 9100
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: DockerfileDebug

