apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
  - image: k8s-ephemeral-storage-metrics
    docker:
      dockerfile: DockerfileDebug

deploy:
  kubectl:
    manifests:
      - k8s-*

#deploy:
#  kubectl:
#    manifests:
#      - DaemonSet*
#profiles:
#  - name: dev
#    patches:
#      - op: replace
#        path: /build/artifacts/0/docker/dockerfile
#        value: DockerfileDebug
#      - op: replace
#        path: /deploy/kubectl/manifests/0
#        value: k8s-pod.yaml
