apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: k8s-ephemeral-storage-metrics
      docker:
        dockerfile: Dockerfile


profiles:
  - name: staging
    deploy:
      helm:
        releases:
          - name: k8s-ephemeral-storage-metrics-staging
            namespace: k8s-ephemeral-storage-metrics-staging
            createNamespace: true
            chartPath: 'charts/k8s-ephemeral-storage-metrics'
            artifactOverrides:
              image: k8s-ephemeral-storage-metrics
    portForward:
      - resourceType: Pod
        resourceName: k8s-ephemeral-storage-metrics
        namespace: k8s-ephemeral-storage-metrics-debug
        port: 9100
        localPort: 9100

  - name: dev
    deploy:
      kubectl:
        manifests:
          - Pod.yaml
    portForward:
      - resourceType: Pod
        resourceName: k8s-ephemeral-storage-metrics
        namespace: k8s-ephemeral-storage-metrics-debug
        port: 9100
        localPort: 9100

  - name: debug
    deploy:
      kubectl:
        manifests:
          - Pod.yaml
    portForward:
      - resourceType: Pod
        resourceName: k8s-ephemeral-storage-metrics
        namespace: k8s-ephemeral-storage-metrics-debug
        port: 9100
        localPort: 9100
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: DockerfileDebug

