apiVersion: skaffold/v2beta29
kind: Config
build:
  artifacts:
    - image: k8s-ephemeral-storage-metrics
      docker:
        dockerfile: DockerfileDebug

deploy:
  kubectl:
    manifests:
      - DaemonSet*
profiles:
  - name: dev
    portForward:
      - resourceType: Pod
        resourceName: k8s-ephemeral-storage-metrics
        namespace: k8s-ephemeral-storage-metrics-debug
        port: 9100
        localPort: 9100
    patches:
      - op: replace
        path: /build/artifacts/0/docker/dockerfile
        value: DockerfileDebug
      - op: replace
        path: /deploy/kubectl/manifests/0
        value: Pod.yaml

