apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
# https://doc.crds.dev/github.com/prometheus-operator/kube-prometheus/monitoring.coreos.com/PodMonitor/v1@v0.7.0
metadata:
  name: {{ .Release.Name }}
  # Change this to the namespace the Prometheus instance is running in
  namespace: {{ .Release.Namespace }}
  labels:
    release: kube-prometheus
    k8s-app: {{ .Release.Name }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      k8s-app: {{ .Release.Name }}
  podMetricsEndpoints:
    - port: http
      interval: {{ .Values.interval }}
      relabelings:
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node_name
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_host_ip
          targetLabel: instance